#!/bin/sh
project_unix_name=introcompatiblizer
if [ -z "$PREFIX" ]; then
  PREFIX=$HOME/.local
fi
prefix="$PREFIX"
lib_root=$prefix/lib
icons_root=$prefix/share/pixmaps

applications_path=$prefix/share/applications

this_data_file_name=introcompatiblizer.py
icon_name=introcompatiblizer.png
my_lib=$lib_root/$project_unix_name

if [ ! -d "$icons_root" ]; then
  mkdir -p "$icons_root"
fi
cp $icon_name "$icons_root/"
if [ ! -d "$my_lib" ]; then
  mkdir -p "$my_lib"
fi
cp $this_data_file_name "$my_lib/"

if [ ! -d "$applications_path" ]; then
  mkdir -p "$applications_path"
fi

cp $project_unix_name.desktop "$applications_path/"

this_bin_path="$my_lib/$this_data_file_name"
if [ -f "$this_bin_path" ]; then
  echo "Successfully installed $this_bin_path"
else
  echo "FAILED to create $this_bin_path"
  exit 1
fi
