@echo off

SET PROGRAM_PY_NAME=introcompatiblizer.py
SET PROGRAMFOLDER_NAME=IntroCompatiblizer
SET DESTFOLDER_FULLNAME=D:\Projects-kivy\%PROGRAMFOLDER_NAME%
SET INSTALLSRCFOLDER_FULLNAME=.
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=E:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=F:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=G:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=H:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=I:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=J:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=K:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=L:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=M:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=N:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=O:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=P:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=Q:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=R:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=S:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=T:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=U:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=V:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=W:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=X:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=Y:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC
SET INSTALLSRCFOLDER_FULLNAME=Z:\IntroCompatiblizer
IF EXIST "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" GOTO FOUNDSRC


echo The install source was not found.
pause


:FOUNDSRC

md "%DESTFOLDER_FULLNAME%"

copy /y "%INSTALLSRCFOLDER_FULLNAME%\EULA.txt" "%DESTFOLDER_FULLNAME%\"
copy /y "%INSTALLSRCFOLDER_FULLNAME%\Intro Compatiblizer.bat" "%DESTFOLDER_FULLNAME%\"
copy /y "%INSTALLSRCFOLDER_FULLNAME%\%PROGRAM_PY_NAME%" "%DESTFOLDER_FULLNAME%\"
copy /y "%INSTALLSRCFOLDER_FULLNAME%\README.md" "%DESTFOLDER_FULLNAME%\"
copy /y "%INSTALLSRCFOLDER_FULLNAME%\WMFormatSDK_eula.txt" "%DESTFOLDER_FULLNAME%\"
copy /y "%INSTALLSRCFOLDER_FULLNAME%\wmvappend.exe" "%DESTFOLDER_FULLNAME%\"
REM copy /y "%INSTALLSRCFOLDER_FULLNAME%\Intro Compatiblizer.bat" "%USERPROFILE%\Desktop\"
